bot_name: "version_check_man"
icon_emoji: ":ok_woman:"
message_text: "Google Play Review:"
web_hook_uri: "<SET YOUR SLACK WEB HOOK URL>"
app_id: "<SET YOUR Google Play App Id"
db_path: "/tmp/review_db"
review_count: 5
